<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Streamline.Core\Streamline.Core.csproj" />
    <ProjectReference Include="..\Streamline.Domain\Streamline.Domain.csproj" />
    <ProjectReference Include="..\Streamline.Application\Streamline.Application.csproj" />
  </ItemGroup>

</Project>
